export const GET_BOOK_REQUEST =  "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAIL = "GET_BOOK_FAIL";

export const GET_SINGLE_BOOK_REQUEST = "GET_SINGLE_BOOK_REQUEST";
export const GET_SINGLE_BOOK_SUCCESS = "GET_SINGLE_BOOK_SUCCESS";
export const GET_SINGLE_BOOK_FAIL = "GET_SINGLE_BOOK_FAIL";

export const CREATE_BOOK_REQUEST = "CREATE_BOOK_REQUEST";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAIL = "CREATE_BOOK_FAIL";
